In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

np.random.seed = 2021
from sklearn.datasets import load_iris
iris = load_iris()
print ('data contains:',iris.keys())
X, y, labels, feature_names  = iris.data, iris.target, iris.target_names, iris['feature_names']
df_iris= pd.DataFrame(X, columns= feature_names) 
df_iris['label'] =  y
features_dict = {k:v for k,v in  enumerate(labels)}
df_iris['label_names'] = df_iris.label.apply(lambda x: features_dict[x])
df_iris

data contains: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label label_names  
0        0      setosa  
1        0      setosa  
2        0      setosa  
3        0      setosa  
4        0      setosa  
..     ...         ...  
145      2   virginica  
146      2   virginica  
147      2   virginica  
148      2   virginica  
149      2   virginica  

[150 rows x 6 columns]

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

print ('X_train.shape=', X_train.shape)
print ('y_train.shape=', y_train.shape)
print ('X_test.shape=', X_test.shape)
print ('y_test.shape=', y_test.shape)

X_train[:5]

X_train.shape= (112, 4)
y_train.shape= (112,)
X_test.shape= (38, 4)
y_test.shape= (38,)


array([[5.9, 3. , 4.2, 1.5],
       [5.8, 2.6, 4. , 1.2],
       [6.8, 3. , 5.5, 2.1],
       [4.7, 3.2, 1.3, 0.2],
       [6.9, 3.1, 5.1, 2.3]])

In [3]:
from sklearn.svm import LinearSVC

clf = LinearSVC(C=1).fit(X, y)
print("train accuracy= {:.3%}".format(clf.score (X, y)))
print  ('b = {}\nw = {}'.format(clf.intercept_, clf.coef_))

train accuracy= 96.667%
b = [ 0.10956294  1.67910569 -1.70960595]
w = [[ 0.18424081  0.45123069 -0.80794388 -0.45071416]
 [ 0.05606358 -0.89801274  0.4085391  -0.96078018]
 [-0.85067477 -0.98663839  1.38090514  1.86534678]]


C:\Users\Maks\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\Maks\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [4]:
from sklearn.svm import SVC
gamma = 1
clf = SVC(C=1, gamma=gamma).fit(X_train, y_train)
train_accuracy = clf.score(X_train, y_train)
print("Train accuracy = {:.3%}".format(train_accuracy))

Train accuracy = 97.321%


In [5]:
clf = SVC(kernel='poly', degree=3).fit(X_train, y_train)

train_accuracy = clf.score(X_train, y_train)
print("Train accuracy = {:.3%}".format(train_accuracy))

Train accuracy = 99.107%


In [6]:
new_instance1 = [[3, 3, 3, 1.3]]
new_instance2 = [[6.7, 3.0, 5.2, 2.2]]

iris_prediction1 = clf.predict(new_instance1)
iris_prediction2 = clf.predict(new_instance2)
print(f"Прогнозована мітка для instance1 linear: {features_dict[iris_prediction1[0]]}")
print(f"Прогнозована мітка для instance2 linear: {features_dict[iris_prediction2[0]]}")

clf = SVC(C=1, gamma=gamma).fit(X_train, y_train)
iris_prediction1 = clf.predict(new_instance1)
iris_prediction2 = clf.predict(new_instance2)
print(f"Прогнозована мітка для instance1 RBF: {features_dict[iris_prediction1[0]]}")
print(f"Прогнозована мітка для instance2 RBF: {features_dict[iris_prediction2[0]]}")

clf = SVC(kernel='poly', degree=3).fit(X_train, y_train)
iris_prediction1 = clf.predict(new_instance1)
iris_prediction2 = clf.predict(new_instance2)
print(f"Прогнозована мітка для instance1 Poly: {features_dict[iris_prediction1[0]]}")
print(f"Прогнозована мітка для instance2 Poly: {features_dict[iris_prediction2[0]]}")

Прогнозована мітка для instance1 linear: versicolor
Прогнозована мітка для instance2 linear: virginica
Прогнозована мітка для instance1 RBF: virginica
Прогнозована мітка для instance2 RBF: virginica
Прогнозована мітка для instance1 Poly: versicolor
Прогнозована мітка для instance2 Poly: virginica
