In [1]:
import re
import pandas as pd
import numpy as np
import os
cwd= os.getcwd()
path = os.path.join(cwd,'data')
def get_sample(fn):
    with open(fn, 'r') as f:
        content = f.read()
    return content
    
fn=  os.path.join(path , 'emailSample1.txt')
content = get_sample(fn)

def word_tokenize(content):
    '''
    content: str - body of mail 
    return: list of tokens (str) e.g. ['>', 'Anyone', 'knows', 'how', 'much', 'it', 'costs', 'to', 'host', 'a']
    '''
    # YOUR_CODE.  Split the content to tokens. You may need re.split()
    # START_CODE 
    tokens = re.split(r'\s+|(?<!\d),.', content)
    # END_CODE 
    
    return tokens
tokens  = word_tokenize('''> Anyone knows how much it costs to host a web portal ?\n>\nWell, it depends on how many visitors you're expecting.\nThis can be anywhere from less than 10 bucks a month to a couple of $100. \nYou should checkout http://www.rackspace.com/ or perhaps Amazon EC2 \nif youre running something big..\n\nTo unsubscribe yourself from this mailing list, send an email to:\ngroupname-unsubscribe@egroups.com\n\n''')
tokens


['>',
 'Anyone',
 'knows',
 'how',
 'much',
 'it',
 'costs',
 'to',
 'host',
 'a',
 'web',
 'portal',
 '?',
 '>',
 'Well',
 'it',
 'depends',
 'on',
 'how',
 'many',
 'visitors',
 "you're",
 'expecting.',
 'This',
 'can',
 'be',
 'anywhere',
 'from',
 'less',
 'than',
 '10',
 'bucks',
 'a',
 'month',
 'to',
 'a',
 'couple',
 'of',
 '$100.',
 'You',
 'should',
 'checkout',
 'http://www.rackspace.com/',
 'or',
 'perhaps',
 'Amazon',
 'EC2',
 'if',
 'youre',
 'running',
 'something',
 'big..',
 'To',
 'unsubscribe',
 'yourself',
 'from',
 'this',
 'mailing',
 'list',
 'send',
 'an',
 'email',
 'to:',
 'groupname-unsubscribe@egroups.com',
 '']

In [2]:
def lower_case(tokens):
    '''
    tokens: ndarry of str
    return: ndarry of tokens in lower case (str)
    '''
    tokens = [token.lower() for token in tokens]

    return tokens

tokens = lower_case(tokens)
tokens

['>',
 'anyone',
 'knows',
 'how',
 'much',
 'it',
 'costs',
 'to',
 'host',
 'a',
 'web',
 'portal',
 '?',
 '>',
 'well',
 'it',
 'depends',
 'on',
 'how',
 'many',
 'visitors',
 "you're",
 'expecting.',
 'this',
 'can',
 'be',
 'anywhere',
 'from',
 'less',
 'than',
 '10',
 'bucks',
 'a',
 'month',
 'to',
 'a',
 'couple',
 'of',
 '$100.',
 'you',
 'should',
 'checkout',
 'http://www.rackspace.com/',
 'or',
 'perhaps',
 'amazon',
 'ec2',
 'if',
 'youre',
 'running',
 'something',
 'big..',
 'to',
 'unsubscribe',
 'yourself',
 'from',
 'this',
 'mailing',
 'list',
 'send',
 'an',
 'email',
 'to:',
 'groupname-unsubscribe@egroups.com',
 '']

In [4]:
def normalize_tokens(tokens):
    '''
    tokens: ndarray of str
    return: ndarray of tokens replaced with corresponding unified words
    '''
    for i in range(len(tokens)):
        # Remove HTML tags
        tokens[i] = re.sub(r'<[^<>]+>', ' ', tokens[i])
        # Mark all numbers as "number"
        tokens[i] = re.sub(r'[0-9]+', 'number', tokens[i])
        # Mark all URLs as "httpaddr"
        tokens[i] = re.sub(r'(http|https)://[^\s]*', 'httpaddr', tokens[i])
        # Mark all email addresses as "emailaddr"
        tokens[i] = re.sub(r'[^\s]+@[^\s]+', 'emailaddr', tokens[i])
        # Replace $ as "dollar"
        tokens[i] = re.sub(r'\$', 'dollar', tokens[i])
        # Get rid of any punctuation
        tokens[i] = re.sub(r'[^\w\s]', '', tokens[i])
        # Remove any non-alphanumeric characters
        tokens[i] = re.sub(r'[^a-zA-Z0-9]', ' ', tokens[i])
    
    return tokens

tokens = normalize_tokens(tokens)
tokens

['',
 'anyone',
 'knows',
 'how',
 'much',
 'it',
 'costs',
 'to',
 'host',
 'a',
 'web',
 'portal',
 '',
 '',
 'well',
 'it',
 'depends',
 'on',
 'how',
 'many',
 'visitors',
 'youre',
 'expecting',
 'this',
 'can',
 'be',
 'anywhere',
 'from',
 'less',
 'than',
 'number',
 'bucks',
 'a',
 'month',
 'to',
 'a',
 'couple',
 'of',
 'dollarnumber',
 'you',
 'should',
 'checkout',
 'httpaddr',
 'or',
 'perhaps',
 'amazon',
 'ecnumber',
 'if',
 'youre',
 'running',
 'something',
 'big',
 'to',
 'unsubscribe',
 'yourself',
 'from',
 'this',
 'mailing',
 'list',
 'send',
 'an',
 'email',
 'to',
 'emailaddr',
 '']

In [5]:
def filter_short_tokens(tokens):
    '''
    tokens: ndarry of str
    return: ndarry of filtered tokens (str)
    '''
    original_tokens_len = len(tokens)
    
    # Keep only tokens that have length > 0
    tokens = [token for token in tokens if len(token) > 0]
   
    print ('Original len= {}\nRemaining len= {}'.format(original_tokens_len, len(tokens)))    
    
    return tokens

tokens = filter_short_tokens(tokens)
tokens

Original len= 65
Remaining len= 61


['anyone',
 'knows',
 'how',
 'much',
 'it',
 'costs',
 'to',
 'host',
 'a',
 'web',
 'portal',
 'well',
 'it',
 'depends',
 'on',
 'how',
 'many',
 'visitors',
 'youre',
 'expecting',
 'this',
 'can',
 'be',
 'anywhere',
 'from',
 'less',
 'than',
 'number',
 'bucks',
 'a',
 'month',
 'to',
 'a',
 'couple',
 'of',
 'dollarnumber',
 'you',
 'should',
 'checkout',
 'httpaddr',
 'or',
 'perhaps',
 'amazon',
 'ecnumber',
 'if',
 'youre',
 'running',
 'something',
 'big',
 'to',
 'unsubscribe',
 'yourself',
 'from',
 'this',
 'mailing',
 'list',
 'send',
 'an',
 'email',
 'to',
 'emailaddr']

In [6]:
from nltk.stem import PorterStemmer

def stem_tokens(tokens):
    '''
    tokens: ndarry of str
    return: ndarry of stemmed tokens e.g. array(['anyon', 'know', 'how', 'much', 'it', 'cost', 'to', 'host', 'a',
       'web', 'portal', 'well', 'it', 'depend', 'on', 'how', 'mani']...
    '''
    stemmer = PorterStemmer()

    # Stem each token in the list
    stemmed_tokens = [stemmer.stem(token) for token in tokens]

    return stemmed_tokens

tokens = stem_tokens(tokens)
tokens

['anyon',
 'know',
 'how',
 'much',
 'it',
 'cost',
 'to',
 'host',
 'a',
 'web',
 'portal',
 'well',
 'it',
 'depend',
 'on',
 'how',
 'mani',
 'visitor',
 'your',
 'expect',
 'thi',
 'can',
 'be',
 'anywher',
 'from',
 'less',
 'than',
 'number',
 'buck',
 'a',
 'month',
 'to',
 'a',
 'coupl',
 'of',
 'dollarnumb',
 'you',
 'should',
 'checkout',
 'httpaddr',
 'or',
 'perhap',
 'amazon',
 'ecnumb',
 'if',
 'your',
 'run',
 'someth',
 'big',
 'to',
 'unsubscrib',
 'yourself',
 'from',
 'thi',
 'mail',
 'list',
 'send',
 'an',
 'email',
 'to',
 'emailaddr']

In [7]:
def get_vocabulary(fn):
    '''
    fn: str - full path to file 
    return: ndarray of str e.g. array(['aa', 'ab', 'abil', ..., 'zdnet', 'zero', 'zip'], dtype=object)
    '''
    vocab_list = pd.read_table(fn, header=None)
    vocab = np.array(vocab_list)[:,1] # first columns is index, select only words column  
    print ('len(vocab)= {:,}'.format(len(vocab)))
    return vocab

fn=  os.path.join(path , 'vocab.txt')
vocab = get_vocabulary(fn)
vocab

len(vocab)= 1,899


array(['aa', 'ab', 'abil', ..., 'zdnet', 'zero', 'zip'], dtype=object)

In [8]:
def represent_features(tokens, vocab):
    '''
    tokens: ndarry of str
    vocab: ndarry of str
    return: ndarry of binary values 1 if word from vocabulary is in mail, 0 otherwise
    '''
    # Initialize an array of zeros with the same length as the vocabulary
    tokens_represented = np.zeros(len(vocab))

    # Iterate through the tokens and set the corresponding index to 1 if the word is in the vocabulary
    for token in tokens:
        if token in vocab:
            index = np.where(vocab == token)[0]
            tokens_represented[index] = 1

    print('{} word(s) from vocab are in the tokens.'.format(np.sum(tokens_represented)))

    return tokens_represented
tokens_represented = represent_features(tokens, vocab)
tokens_represented


44.0 word(s) from vocab are in the tokens.


array([0., 0., 0., ..., 0., 0., 0.])

In [9]:
def preprocess(content, vocab):
    '''
    content: str - body of mail 
    vocab: ndarray of str - list of considered words 
    '''
    # Tokenize content
    tokens = word_tokenize(content)

    # Make tokens lowercase
    tokens = lower_case(tokens)

    # Normalize tokens
    tokens = normalize_tokens(tokens)

    # Remove zero length tokens
    tokens = filter_short_tokens(tokens)

    # Stem words
    tokens = stem_tokens(tokens)

    # Convert to binary array of features
    tokens_represented = represent_features(tokens, vocab)
    
    return tokens_represented
preprocess (content,vocab)

Original len= 65
Remaining len= 61
44.0 word(s) from vocab are in the tokens.


array([0., 0., 0., ..., 0., 0., 0.])

In [10]:
from scipy.io import loadmat
fn=  os.path.join(path , 'spamTrain.mat')

mat= loadmat(fn)
X_train= mat['X']
y_train= mat['y'].ravel()

print ('X_train.shape= {}',X_train.shape)
print ('y_train.shape= {}',y_train.shape)

fn=  os.path.join(path , 'spamTest.mat')
mat= loadmat(fn)
X_test = mat['Xtest']
y_test = mat['ytest'].ravel() 

print ('X_test.shape= {}',X_test.shape)
print ('y_test.shape= {}',y_test.shape)
index = 0 
print ('Sample with index  ={}: \n{}'.format(index, X_train[index]))

X_train.shape= {} (4000, 1899)
y_train.shape= {} (4000,)
X_test.shape= {} (1000, 1899)
y_test.shape= {} (1000,)
Sample with index  =0: 
[0 0 0 ... 0 0 0]


In [11]:
from sklearn.svm import SVC 
from sklearn.svm import LinearSVC

C = .1
clf= LinearSVC(C=C)
clf.fit(X_train,y_train)
print ('Score train= {}'.format(clf.score(X_train,y_train)))
print ('Score test= {}'.format(clf.score(X_test,y_test)))

Score train= 0.99975
Score test= 0.992


C:\Users\Maks\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


In [12]:
# Get the indices of the top 20 largest coefficients
top_indices = clf.coef_[0].argsort()[-20:][::-1]

# Get the corresponding words from the vocabulary
top_spam_contributors = vocab[top_indices]

print (top_spam_contributors)

['our' 'remov' 'click' 'basenumb' 'guarante' 'visit' 'bodi' 'will'
 'numberb' 'price' 'dollar' 'nbsp' 'below' 'lo' 'most' 'send' 'dollarnumb'
 'credit' 'wi' 'hour']


In [13]:
for sfn in ['emailSample1.txt', 'emailSample2.txt', 'spamSample1.txt', 'spamSample2.txt']:
    fn = os.path.join(path, sfn)
    content = get_sample(fn)

    # Preprocess the sample
    preprocessed_sample = preprocess(content, vocab)

    # Get prediction (0 for not spam, 1 for spam) using the trained SVM model (clf)
    prediction = clf.predict([preprocessed_sample])[0]

    print('{} is {}\n'.format(sfn, ('Not Spam', 'Spam')[prediction]))

print('Latter sample:\n{1}\n{0}\n{1}'.format(content, '='*50))


Original len= 65
Remaining len= 61
44.0 word(s) from vocab are in the tokens.
emailSample1.txt is Not Spam

Original len= 228
Remaining len= 222
122.0 word(s) from vocab are in the tokens.
emailSample2.txt is Not Spam

Original len= 99
Remaining len= 97
46.0 word(s) from vocab are in the tokens.
spamSample1.txt is Spam

Original len= 35
Remaining len= 31
18.0 word(s) from vocab are in the tokens.
spamSample2.txt is Spam

Latter sample:
Best Buy Viagra Generic Online

Viagra 100mg x 60 Pills $125, Free Pills & Reorder Discount, Top Selling 100% Quality & Satisfaction guaranteed!

We accept VISA, Master & E-Check Payments, 90000+ Satisfied Customers!
http://medphysitcstech.ru



